name: Backup Metadata

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1

      - name: Save Private Key
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" | awk '{print}' > server.key

      - name: Authenticate with JWT
        run: |
          sfdx auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile server.key --username ${{ secrets.SF_USERNAME }} --instanceurl ${{ secrets.SF_INSTANCE_URL }} --setalias jwtOrg

      - name: Retrieve metadata
        run: |
          mkdir mdapi_output
          sfdx force:source:retrieve -x manifest/package.xml -u jwtOrg

            - name: Commit & Push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add .
          git commit -m "Automated metadata backup" || echo "Nothing to commit"
          git push

