# Trigger refresh
name: Backup Metadata

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1

      - name: Authenticate with JWT
        run: |
          echo "$SF_JWT_KEY" > server.key
          sfdx auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile server.key --username ${{ secrets.SF_USERNAME }} --instanceurl https://login.salesforce.com --setalias jwtOrg

      - name: Retrieve metadata
        run: |
          mkdir mdapi_output
          sfdx force:source:retrieve -x manifest/package.xml -u jwtOrg

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Automated metadata backup"
          git push
