name: Backup Metadata

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1

      - name: Create JWT key file
        run: |
          cat <<EOF > server.key
          ${{ secrets.SF_JWT_KEY }}
          EOF

      - name: Authenticate to Salesforce Org
        run: |
          sfdx auth:jwt:grant \
            --client-id ${{ secrets.SF_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url https://login.salesforce.com \
            --alias jwtOrg

      - name: Retrieve metadata
        run: |
          mkdir -p mdapi_output
          sfdx force:source:retrieve -x manifest/package.xml -u jwtOrg

      - name: Commit & Push
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          # 👇 Step 3: Show the current git remote being used
          git remote show origin
          git add .
          git commit -m "Automated metadata backup" || echo "Nothing to commit"
          git push
